title: Robertson McClure
description: >
  | Robertson McClure is a student, software developer and volleyball coach. He writes about what'
permalink: /:title/
social:
  twitter: robertsonmcclur
  github: robertsonmcclure
  instagram: robertsonmcclure
analytics: UA-79717942-1
