title: 'Robertson McClure'
description: 'Robertson McClure is a student, software developer and volleyball coach.'
url: 'https://robertsonmcclure.ca'
destination: _site
image: cn-tower.jpg
permalink: /:title/
markdown: kramdown
sass:
  style: compressed
social:
  - account: fa-github
    link: https://github.com/robertsonmcclure
  - account: fa-twitter
    link: https://twitter.com/robertsonmcclur
  - account: fa-instagram
    link: https://instagram.com/robertsonmcclure
  - account: fa-linkedin
    link: https://linkedin.com/in/robertsonmcclure
collections:
- projects
