# Site settings
title: 'Robertson McClure'
description: 'Robertson McClure - Software Developer'
about: 'Software Developer'
url: 'http://robertsonmcclure.ca'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Robertson McClure'
  email: r.mcclure@mail.utoronto.ca
  twitter_username: robertsonmcclur
  instagram_username: robertsonmcclure
  github_username:  robertsonmcclure
  linkedin_username:  robertsonmcclure

collections:
- projects

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
