title: Robertson McClure
email: r.mcclure@mail.utoronto.ca
description: Robertson McClure is a student, software developer and volleyball coach.
about: Software Developer  Volleyball Coach
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robertsonmcclure.ca" # the base hostname & protocol for your site

name: 'Robertson McClure'
bio: Robertson McClure is a student, software developer and volleyball coach.
author_image: "/assets/images/author.jpg"

twitter_username: robertsonmcclur
github_username:  robertsonmcclure
instagram_username: robertsonmcclure

permalink: /:title/
markdown: kramdown
kramdown:
  parse_block_html: true
