# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robertson McClure
email: r.mcclure@mail.utoronto.ca
description:
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:title"
url: "http://robertsonmcclure.ca" # the base hostname & protocol for your site
twitter_username: robertsonmcclur
github_username:  robertsonmcclure 

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

collections:
  - books
