# Site
title: Robertson McClure
email: r.mcclure@mail.utoronto.ca
description: eclectically everything
url: http://robertsonmcclure.ca
baseurl: ""

# Jekyll
permalink: "/:title"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Google Analytics
google-analytics: UA-79717942-1

# Social Links
twitter:      robertsonmcclur
github:       robertsonmcclure
instagram:    robertsonmcclure
linkedin:     robertsonmcclure

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-assets
