title: 'Robertson McClure'
description: 'Robertson McClure is a student, software developer and volleyball coach.'
url: 'http://robertsonmcclure.ca'
destination: _site
permalink: /:title/
markdown: kramdown
sass:
  style: compressed
social:
  - account: github
    link: https://github.com/robertsonmcclure
  - account: twitter
    link: https://twitter.com/robertsonmcclur
  - account: instagram
    link: https://instagram.com/robertsonmcclure
  - account: linkedin
    link: https://linkedin.com/in/robertsonmcclure
collections:
- projects
